# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [10]:
import numpy as np

a = np.arange(10)
print(a.sum())
print(a.sum().dtype)
print(a)
print(np.sum(a))
print(np.sum(a).dtype)
print(a)
print(sum(a)) 
print(sum(a).dtype)
print(a)

45
int64
[0 1 2 3 4 5 6 7 8 9]
45
int64
[0 1 2 3 4 5 6 7 8 9]
45
int64
[0 1 2 3 4 5 6 7 8 9]


相同，皆不會影響原陣列且回傳int64 </br>
其中sum(a)的sum()為python內建的函數

### 2. 請對一個 5x5 的隨機矩陣作一般化的操作。


In [25]:
A = np.random.random((5, 5)) * 7
print(A)
# normalize到0 ~ 1的區間
A = (A - A.min()) / (A.max() - A.min())
print("\nNormalization:")
print(A)

[[2.40379576 2.66825904 4.51136763 0.1100697  3.29499616]
 [6.27656934 3.40334005 2.64191396 3.05398082 0.86033251]
 [1.67033154 2.43911839 4.65558723 5.19741738 0.53228335]
 [6.95051052 2.64657297 0.80250444 3.89341406 3.23120433]
 [5.7111863  1.0443943  3.41355915 0.74143031 3.10501804]]

Normalization:
[[0.33531846 0.37398019 0.64342314 0.         0.46560252]
 [0.90147694 0.48144125 0.37012882 0.43036863 0.10968048]
 [0.22809376 0.34048225 0.66450652 0.74371635 0.06172316]
 [1.         0.37080991 0.10122663 0.55308488 0.45627683]
 [0.81882393 0.13658836 0.48293517 0.09229824 0.43782973]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [18]:
a = np.arange(10)
print(a)
a[a.argmax()] = -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8 -1]
